/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package d2l.kt

import java.net.URL
import kotlin.test.Test
import kotlin.test.assertEquals

class D2LAuthTest {

    @Test
    fun testCreateHMAC() {
        val hmac = D2LAuth.createHMAC("hallo", "Hello")
        assertEquals("6WJ8SavVfZB-MhJX6uejaA5P4zaXh0ZrpbMAdfYwbVA", hmac)
    }

    @Test
    fun testBuildLoginURL() {
        val url = D2LAuth.buildLoginURL("mockAppID", "mockAppKey", URL("https://ufora.ugent.be"), URL("https://mock.url/trustedURL"))
        val expectedURL = URL("https://ufora.ugent.be/d2l/auth/api/token?x_b=qF35MFcEzD3DJ1IoPIAx7CC8FgtvG-liC-NuSttQbXA&x_target=https%3A%2F%2Fmock.url%2FtrustedURL&type=mobile&x_a=mockAppID")
        assertEquals(expectedURL, url)
    }

}
